### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by cchantep** [SlyngDK/reactivemongo-cursor-retry-bug#1]
```
sbt:reactivemongo-cursor-retry-bug> testOnly
[info] Updating ...
[info] Done updating.
[info] Compiling 1 Scala source to /private/tmp/reactivemongo-cursor-retry-bug/target/scala-2.12/test-classes ...
[info] Done compiling.
mars 16, 2019 8:54:20 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory
mars 16, 2019 8:54:20 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: Retrying request to {}->unix://localhost:80
mars 16, 2019 8:54:20 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory
mars 16, 2019 8:54:20 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: Retrying request to {}->unix://localhost:80
mars 16, 2019 8:54:20 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory
mars 16, 2019 8:54:20 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: Retrying request to {}->unix://localhost:80
mars 16, 2019 8:54:20 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory
mars 16, 2019 8:54:20 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: Retrying request to {}->unix://localhost:80
mars 16, 2019 8:54:20 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory
mars 16, 2019 8:54:20 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: Retrying request to {}->unix://localhost:80
mars 16, 2019 8:54:20 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory
mars 16, 2019 8:54:20 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: Retrying request to {}->unix://localhost:80
[info] CursorRetrySpec:
[info] Cursor
[info] CursorRetrySpec *** ABORTED ***
[info]   com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory
[info]   at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2843)
[info]   at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2697)
[info]   at com.spotify.docker.client.DefaultDockerClient.listContainers(DefaultDockerClient.java:621)
[info]   at CursorRetrySpec.$anonfun$getContainer$1(CursorRetrySpec.scala:145)
[info]   at CursorRetrySpec$$Lambda$4660/1345888932.apply(Unknown Source)
[info]   at scala.Option.flatMap(Option.scala:188)
[info]   at CursorRetrySpec.getContainer(CursorRetrySpec.scala:146)
[info]   at CursorRetrySpec.$anonfun$new$2(CursorRetrySpec.scala:40)
[info]   at CursorRetrySpec.$anonfun$new$2$adapted(CursorRetrySpec.scala:38)
[info]   at CursorRetrySpec$$Lambda$4659/793433324.apply(Unknown Source)
[info]   ...
[info]   Cause: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory
[info]   at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
[info]   at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
[info]   at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
[info]   at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2695)
[info]   at com.spotify.docker.client.DefaultDockerClient.listContainers(DefaultDockerClient.java:621)
[info]   at CursorRetrySpec.$anonfun$getContainer$1(CursorRetrySpec.scala:145)
[info]   at CursorRetrySpec$$Lambda$4660/1345888932.apply(Unknown Source)
[info]   at scala.Option.flatMap(Option.scala:188)
[info]   at CursorRetrySpec.getContainer(CursorRetrySpec.scala:146)
[info]   at CursorRetrySpec.$anonfun$new$2(CursorRetrySpec.scala:40)
[info]   ...

```

**Comment by SlyngDK** [comment]
You need a running docker.

**Comment by cchantep** [comment]
That's the case
